""" gui.py --

 UI generated by GUI Builder Build 146 on 2012-08-23 11:22:28 from:
    E:/gitCode/my_code/gui_ssh/gui.ui
 This file is auto-generated.  Only the code within
    '# BEGIN USER CODE (global|class)'
    '# END USER CODE (global|class)'
 and code inside the callback subroutines will be round-tripped.
 The 'main' function is reserved.
"""

from Tkinter import *
from gui_ui import Gui

# BEGIN USER CODE global

# END USER CODE global

class CustomGui(Gui):
    pass

    # BEGIN CALLBACK CODE
    # ONLY EDIT CODE INSIDE THE def FUNCTIONS.

    # _canvas_1_xscrollcommand --
    #
    # Callback to handle _canvas_1 widget option -xscrollcommand
    def _canvas_1_xscrollcommand(self, *args):
        pass

    # _canvas_1_yscrollcommand --
    #
    # Callback to handle _canvas_1 widget option -yscrollcommand
    def _canvas_1_yscrollcommand(self, *args):
        pass

    # _listbox_1_xscrollcommand --
    #
    # Callback to handle _listbox_1 widget option -xscrollcommand
    def _listbox_1_xscrollcommand(self, *args):
        pass

    # END CALLBACK CODE

    # BEGIN USER CODE class

    # END USER CODE class

def main():
    # Standalone Code Initialization
    # DO NOT EDIT
    try: userinit()
    except NameError: pass
    root = Tk()
    demo = CustomGui(root)
    root.title('gui')
    try: run()
    except NameError: pass
    root.protocol('WM_DELETE_WINDOW', root.quit)
    root.mainloop()

if __name__ == '__main__': main()
