""" gui_ui.py --

 UI generated by GUI Builder Build 146 on 2012-08-23 11:22:28 from:
    E:/gitCode/my_code/gui_ssh/gui.ui
THIS IS AN AUTOGENERATED FILE AND SHOULD NOT BE EDITED.
The associated callback file should be modified instead.
"""

import Tkinter
import os # needed for relative image paths

# Using new-style classes: create empty base class object
# for compatibility with older python interps
#if sys.version_info < (2, 2):
#    class object:
#        pass

class Gui(object):
    _images = [] # Holds image refs to prevent GC
    def __init__(self, root):


        # Widget Initialization
        self._frame_1 = Tkinter.Frame(root,
        )
        self._label_1 = Tkinter.Label(root,
            text = "server list",
        )
        self._listbox_1 = Tkinter.Listbox(root,
            height = 0,
            selectmode = "single",
            width = 0,
        )
        self._canvas_1 = Tkinter.Canvas(root,
            height = 0,
            width = 0,
        )

        # widget commands

        self._listbox_1.configure(
            xscrollcommand = self._listbox_1_xscrollcommand
        )
        self._listbox_1.configure(
            yscrollcommand = self.scrollbar.set
        )
        self._canvas_1.configure(
            xscrollcommand = self._canvas_1_xscrollcommand
        )
        self._canvas_1.configure(
            yscrollcommand = self._canvas_1_yscrollcommand
        )


        # Geometry Management
        self._frame_1.grid(
            in_    = root,
            column = 2,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._label_1.grid(
            in_    = root,
            column = 1,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = ""
        )
        self._listbox_1.grid(
            in_    = root,
            column = 1,
            row    = 2,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )
        self._canvas_1.grid(
            in_    = root,
            column = 2,
            row    = 1,
            columnspan = 1,
            ipadx = 0,
            ipady = 0,
            padx = 0,
            pady = 0,
            rowspan = 1,
            sticky = "news"
        )


        # Resize Behavior
        root.grid_rowconfigure(1, weight = 0, minsize = 40, pad = 0)
        root.grid_rowconfigure(2, weight = 0, minsize = 645, pad = 0)
        root.grid_columnconfigure(1, weight = 0, minsize = 256, pad = 0)
        root.grid_columnconfigure(2, weight = 0, minsize = 818, pad = 0)


