{'elib/*',    
    [debug_info,   
    {i,"include"},   
    {outdir,"ebin"}   
    ]}.

{'examples/*',    
    [debug_info,   
    {i,"include"},   
    {outdir,"ebin"}   
    ]}.    

{'lib/erlapi/*',    
    [debug_info,   
    {i,"include"},   
    {outdir,"ebin"}   
    ]}.